dist: trusty
language: java
jdk: oraclejdk11

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

addons:
  sonarcloud:
    organization: "mivek-github"
    token: ${SONARCLOUD_TOKEN}


before_install:
  # Retrieve keys only if build is not on a pull request
  - bash scripts/before_install.sh

install:
  - mvn compile test-compile

script:
  # If the branch is master then the deploy goal is used otherwise the maven install is used
  # Test against oracledk 8
  - jdk_switcher use oraclejdk8
  - mvn clean verify
  # Test against openjdk 8
  - jdk_switcher use openjdk8
  - mvn clean verify
  # Test against oracle jdk 11
  - export JAVA_HOME=$HOME/oraclejdk11
  - $TRAVIS_BUILD_DIR/install-jdk.sh --install oraclejdk11 --target $JAVA_HOME
  - bash scripts/script.sh

before_deploy:
  - VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

deploy:
  provider: releases
  file_glob: true
  file: /**/target/*.jar
  api_key: $GITHUB_OATH
  skip_cleanup: true
  draft: true
  name: ${VERSION}
  on:
    branch: master
